version: '3.8'

services:
  redis:
    image: redis:7.2.5
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "mypassword"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: